/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations, Stars, PerspectiveCamera } from '@react-three/drei'
import { GLTF } from 'three-stdlib'



// import "./styles.css";
// import { Canvas } from "@react-three/fiber";
// import { useLoader } from "@react-three/fiber";
import {
    Canvas,
    useFrame,
    useThree,
    extend,
    useLoader,
} from "@react-three/fiber";
// import { OrbitControls } from "three/examples/jsm/controls/OrbitControls";
// extend({ OrbitControls });
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { Suspense } from "react";
import { Environment, OrbitControls, Lightformer } from "@react-three/drei";
import useGrayScaleMode from "@hooks/useGrayScaleMode";
import Astronaut3D from "../utils/Astronaut3D";

type GLTFResult = GLTF & {
    nodes: {
        radio_tele002: THREE.Mesh
        Plane001_1: THREE.Mesh
        Plane001_2: THREE.Mesh
        Plane001_3: THREE.Mesh
        Plane001_4: THREE.Mesh
        Plane001_5: THREE.Mesh
        Plane001_6: THREE.Mesh
        Plane001_7: THREE.Mesh
        Plane001_8: THREE.Mesh
        Plane001_9: THREE.Mesh
        Plane001_10: THREE.Mesh
        Mesh051: THREE.Mesh
        Mesh051_1: THREE.Mesh
        Object_18: THREE.Mesh
        Object_18_1: THREE.Mesh
        Object_18_2: THREE.Mesh
        Object_18_3: THREE.Mesh
        Object_18_4: THREE.Mesh
        Object_18_5: THREE.Mesh
        Object_18_6: THREE.Mesh
        Object_18_7: THREE.Mesh
        Object_18_8: THREE.Mesh
        Object_18_9: THREE.Mesh
        Object_18_10: THREE.Mesh
        Object_18_11: THREE.Mesh
        Object_18_12: THREE.Mesh
        Object_18_13: THREE.Mesh
        Object_18_14: THREE.Mesh
        Object_18_15: THREE.Mesh
        Object_18_16: THREE.Mesh
        Object_18_17: THREE.Mesh
        Object_18_18: THREE.Mesh
        Object_18_19: THREE.Mesh
        Object_18_20: THREE.Mesh
        Object_18_21: THREE.Mesh
        Object_18001: THREE.Mesh
        Object_18001_1: THREE.Mesh
        Object_18001_2: THREE.Mesh
        Object_18001_3: THREE.Mesh
        Object_18001_4: THREE.Mesh
        Object_18001_5: THREE.Mesh
        Object_18001_6: THREE.Mesh
        Object_18001_7: THREE.Mesh
        Object_18001_8: THREE.Mesh
        Object_18001_9: THREE.Mesh
        Object_18001_10: THREE.Mesh
        Object_18001_11: THREE.Mesh
        Object_18001_12: THREE.Mesh
        Object_18001_13: THREE.Mesh
        Object_18001_14: THREE.Mesh
        Object_18001_15: THREE.Mesh
        Object_18001_16: THREE.Mesh
        Object_18001_17: THREE.Mesh
        Object_18002: THREE.Mesh
        Object_18002_1: THREE.Mesh
        Object_18002_2: THREE.Mesh
        Object_18002_3: THREE.Mesh
        Object_18002_4: THREE.Mesh
        Object_18002_5: THREE.Mesh
        Object_18002_6: THREE.Mesh
        Object_18002_7: THREE.Mesh
        Object_18002_8: THREE.Mesh
        Object_18002_9: THREE.Mesh
        Object_18002_10: THREE.Mesh
        Object_18002_11: THREE.Mesh
        Object_18002_12: THREE.Mesh
        Object_18002_13: THREE.Mesh
        Object_18002_14: THREE.Mesh
        Object_18002_15: THREE.Mesh
        Object_18002_16: THREE.Mesh
        Object_18002_17: THREE.Mesh
        Object_18002_18: THREE.Mesh
        Object_18002_19: THREE.Mesh
        Object_18002_20: THREE.Mesh
        Object_18002_21: THREE.Mesh
        Object_18003: THREE.Mesh
        Object_18003_1: THREE.Mesh
        Object_18003_2: THREE.Mesh
        Object_18003_3: THREE.Mesh
        Object_18003_4: THREE.Mesh
        Object_18003_5: THREE.Mesh
        Object_18003_6: THREE.Mesh
        Object_18003_7: THREE.Mesh
        Object_18003_8: THREE.Mesh
        Object_18003_9: THREE.Mesh
        Object_18003_10: THREE.Mesh
        Object_18003_11: THREE.Mesh
        Object_18003_12: THREE.Mesh
        Object_18003_13: THREE.Mesh
        Object_18003_14: THREE.Mesh
        Object_18003_15: THREE.Mesh
        Object_18003_16: THREE.Mesh
        Object_18003_17: THREE.Mesh
        tower004: THREE.Mesh
        Mesh090: THREE.Mesh
        Mesh090_1: THREE.Mesh
        Mesh090_2: THREE.Mesh
        Mesh090_3: THREE.Mesh
        Mesh003: THREE.Mesh
        Mesh003_1: THREE.Mesh
        Mesh011: THREE.Mesh
        Mesh011_1: THREE.Mesh
        Mesh012: THREE.Mesh
        Mesh012_1: THREE.Mesh
        Mesh013: THREE.Mesh
        Mesh013_1: THREE.Mesh
        Mesh015: THREE.Mesh
        Mesh015_1: THREE.Mesh
        Mesh016: THREE.Mesh
        Mesh016_1: THREE.Mesh
        Mesh016_2: THREE.Mesh
        Mesh016_3: THREE.Mesh
        Mesh016_4: THREE.Mesh
        Mesh016_5: THREE.Mesh
        Mesh016_6: THREE.Mesh
        Mesh016_7: THREE.Mesh
        Mesh016_8: THREE.Mesh
        Mesh017: THREE.Mesh
        Mesh017_1: THREE.Mesh
        Mesh017_2: THREE.Mesh
        Mesh017_3: THREE.Mesh
        Mesh017_4: THREE.Mesh
        Mesh017_5: THREE.Mesh
        Mesh023: THREE.Mesh
        Mesh023_1: THREE.Mesh
        Mesh024: THREE.Mesh
        Mesh024_1: THREE.Mesh
        Mesh024_2: THREE.Mesh
        Mesh025: THREE.Mesh
        Mesh025_1: THREE.Mesh
        Cube_001_Bridge_0001: THREE.Mesh
        Cube_001_Rope_0001: THREE.Mesh
        Mesh029: THREE.Mesh
        Mesh029_1: THREE.Mesh
        Planet_Snow_0001: THREE.Mesh
        Planet_Water_0001: THREE.Mesh
        Planet_Sand_0003: THREE.Mesh
        Mesh035: THREE.Mesh
        Mesh035_1: THREE.Mesh
        Mesh035_2: THREE.Mesh
        Mesh036: THREE.Mesh
        Mesh036_1: THREE.Mesh
        Mesh036_2: THREE.Mesh
        Mesh036_3: THREE.Mesh
        Plane002: THREE.Mesh
        Plane003: THREE.Mesh
        Mesh052: THREE.Mesh
        Mesh052_1: THREE.Mesh
        Mesh052_2: THREE.Mesh
        Mesh052_3: THREE.Mesh
        Mesh052_4: THREE.Mesh
        Mesh052_5: THREE.Mesh
        Mesh052_6: THREE.Mesh
        Mesh052_7: THREE.Mesh
        Mesh052_8: THREE.Mesh
        Object_10: THREE.Mesh
        Cylinder005: THREE.Mesh
        Cylinder006: THREE.Mesh
        ['buffer-0-mesh-0001']: THREE.Mesh
        ['buffer-0-mesh-0001_1']: THREE.Mesh
        airplane: THREE.Mesh
        rollet_table002: THREE.Mesh
        Mesh077: THREE.Mesh
        Mesh077_1: THREE.Mesh
    }
    materials: {
        radio: THREE.MeshStandardMaterial
        Walls: THREE.MeshStandardMaterial
        ['Yellow Plaster']: THREE.MeshStandardMaterial
        ['Green Roof']: THREE.MeshStandardMaterial
        ['Gray Cement']: THREE.MeshStandardMaterial
        ['Black Doors']: THREE.MeshStandardMaterial
        ['Brown Roof']: THREE.MeshStandardMaterial
        Glass: THREE.MeshStandardMaterial
        ['Dark Gray Cement.001']: THREE.MeshStandardMaterial
        ['Water.001']: THREE.MeshStandardMaterial
        ['Grass.001']: THREE.MeshStandardMaterial
        basepine: THREE.MeshStandardMaterial
        pinballm: THREE.MeshStandardMaterial
        ['lambert30SG.001']: THREE.MeshBasicMaterial
        ['initialShadingGroup.001']: THREE.MeshBasicMaterial
        ['lambert10SG.001']: THREE.MeshBasicMaterial
        ['lambert16SG.001']: THREE.MeshBasicMaterial
        ['lambert17SG.001']: THREE.MeshBasicMaterial
        ['lambert18SG.001']: THREE.MeshBasicMaterial
        ['lambert21SG.001']: THREE.MeshBasicMaterial
        ['lambert27SG.001']: THREE.MeshBasicMaterial
        ['lambert29SG.001']: THREE.MeshBasicMaterial
        ['lambert11SG.001']: THREE.MeshBasicMaterial
        ['lambert13SG.001']: THREE.MeshBasicMaterial
        ['lambert14SG.001']: THREE.MeshBasicMaterial
        ['lambert15SG.001']: THREE.MeshBasicMaterial
        ['lambert22SG.001']: THREE.MeshBasicMaterial
        ['lambert23SG.001']: THREE.MeshBasicMaterial
        ['lambert28SG.001']: THREE.MeshBasicMaterial
        ['lambert3SG.001']: THREE.MeshBasicMaterial
        ['lambert4SG.001']: THREE.MeshBasicMaterial
        ['lambert5SG.001']: THREE.MeshBasicMaterial
        ['lambert6SG.001']: THREE.MeshBasicMaterial
        ['lambert8SG.001']: THREE.MeshBasicMaterial
        ['pasted__pasted__lambert8SG1.001']: THREE.MeshBasicMaterial
        tower: THREE.MeshStandardMaterial
        stadium: THREE.MeshStandardMaterial
        car1: THREE.MeshStandardMaterial
        windows: THREE.MeshStandardMaterial
        car2: THREE.MeshStandardMaterial
        Sail_Boat_Wood: THREE.MeshStandardMaterial
        Sail_Boat_Sail: THREE.MeshStandardMaterial
        Tree_Bark: THREE.MeshStandardMaterial
        House_Chimney: THREE.MeshStandardMaterial
        Snow: THREE.MeshStandardMaterial
        House_Roof: THREE.MeshStandardMaterial
        House: THREE.MeshStandardMaterial
        House_Door: THREE.MeshStandardMaterial
        Tree_Leaves: THREE.MeshStandardMaterial
        MountainNorth: THREE.MeshStandardMaterial
        Grass: THREE.MeshStandardMaterial
        Pyramid: THREE.MeshStandardMaterial
        Bridge: THREE.MeshStandardMaterial
        Rope: THREE.MeshStandardMaterial
        Water: THREE.MeshStandardMaterial
        Sand: THREE.MeshStandardMaterial
        Asphalt: THREE.MeshStandardMaterial
        ['Pavement.001']: THREE.MeshStandardMaterial
        ['stadium grounds']: THREE.MeshStandardMaterial
        road: THREE.MeshStandardMaterial
        ['Material #27']: THREE.MeshStandardMaterial
        ['Material #28']: THREE.MeshStandardMaterial
        ['Material #29']: THREE.MeshStandardMaterial
        flame1: THREE.MeshStandardMaterial
        ['Material #30']: THREE.MeshStandardMaterial
        LaunchPad: THREE.MeshStandardMaterial
        ['flame2.001']: THREE.MeshStandardMaterial
        flame3: THREE.MeshStandardMaterial
        Astronaut: THREE.MeshStandardMaterial
        ['TextureGrid.001']: THREE.MeshStandardMaterial
        ['Windmill.002']: THREE.MeshStandardMaterial
        ['09___Default']: THREE.MeshStandardMaterial
        ['08___Default']: THREE.MeshStandardMaterial
        ['initialShadingGroup.002']: THREE.MeshStandardMaterial
        ['rollet table.003']: THREE.MeshStandardMaterial
        Skyscraper: THREE.MeshStandardMaterial
        SkyscraperWindow: THREE.MeshStandardMaterial
    }
}

type ActionName = 'Cylinder.006Action'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

// type ActionName = 'Cylinder.006Action'
// type GLTFActions = Record<ActionName, THREE.AnimationAction>

const Model2 = ({ ...props }: JSX.IntrinsicElements['group']) => {
    const group = useRef<THREE.Group>(null)
    const { nodes, materials, animations } = useGLTF("/Globe_v4.5.2.glb") as GLTFResult
    // const { actions } = useAnimations<GLTFActions>(animations, group)
    const ref = useRef<THREE.Group>(null);
    const turbineBlade = useRef<THREE.Mesh<THREE.BufferGeometry, THREE.Material | THREE.Material[]>>(null);
    const satellite = useRef<THREE.Group>(null);

    // const [grayscaleMode, setGrayscaleMode] = useGrayScaleMode();
    var t = 0;
    useFrame(() => {
        // ref.current.position.x += 0.5;
        // if (group.current !== null)
        //     group.current.rotation.x += 0.001;
        if (ref.current !== null) {
            ref.current.rotation.y += 0.001;
            ref.current.rotation.z += 0.001;
        }
        if (turbineBlade.current !== null) {
            // c1.current.rotation.z += 0.01;
            turbineBlade.current.rotation.x -= 0.1;
            // turbineBlade.current.color = new THREE.Color(0x00ffff);
        }
        if (satellite.current !== null) {
            t += 0.006;
            satellite.current.rotation.y -= 0.006;
            satellite.current.position.x = 3 * Math.cos(t) + 0;
            satellite.current.position.z = 3 * Math.sin(t) + 0; // These to strings make it work
        }

        // if (ref.current.position.x > 300) {
        //   ref.current.position.x = -300;
        // }
    });

    return (
        <>
            <group ref={group} {...props} dispose={null}>
                <group ref={ref} name="Scene">
                    <mesh name="radio_tele002" geometry={nodes.radio_tele002.geometry} material={materials.radio} rotation={[-0.43, 0.37, -1.86]} scale={0.5} />
                    <group name="Plane001" rotation={[1.64, 0.11, -2.88]} scale={0.75}>
                        <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials.Walls} />
                        <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={materials['Yellow Plaster']} />
                        <mesh name="Plane001_3" geometry={nodes.Plane001_3.geometry} material={materials['Green Roof']} />
                        <mesh name="Plane001_4" geometry={nodes.Plane001_4.geometry} material={materials['Gray Cement']} />
                        <mesh name="Plane001_5" geometry={nodes.Plane001_5.geometry} material={materials['Black Doors']} />
                        <mesh name="Plane001_6" geometry={nodes.Plane001_6.geometry} material={materials['Brown Roof']} />
                        <mesh name="Plane001_7" geometry={nodes.Plane001_7.geometry} material={materials.Glass} />
                        <mesh name="Plane001_8" geometry={nodes.Plane001_8.geometry} material={materials['Dark Gray Cement.001']} />
                        <mesh name="Plane001_9" geometry={nodes.Plane001_9.geometry} material={materials['Water.001']} />
                        <mesh name="Plane001_10" geometry={nodes.Plane001_10.geometry} material={materials['Grass.001']} />
                    </group>
                    <group name="basepin001" position={[-1.76, -0.32, -0.7]} rotation={[1.66, 0.25, 1.89]} scale={0.5}>
                        <mesh name="Mesh051" geometry={nodes.Mesh051.geometry} material={materials.basepine} />
                        <mesh name="Mesh051_1" geometry={nodes.Mesh051_1.geometry} material={materials.pinballm} />
                    </group>
                    <group name="Object_21" position={[-0.16, -1.87, 0.23]} rotation={[1.53, -0.09, -0.14]} scale={0.5}>
                        <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['lambert30SG.001']} />
                        <mesh name="Object_18_1" geometry={nodes.Object_18_1.geometry} material={materials['initialShadingGroup.001']} />
                        <mesh name="Object_18_2" geometry={nodes.Object_18_2.geometry} material={materials['lambert10SG.001']} />
                        <mesh name="Object_18_3" geometry={nodes.Object_18_3.geometry} material={materials['lambert16SG.001']} />
                        <mesh name="Object_18_4" geometry={nodes.Object_18_4.geometry} material={materials['lambert17SG.001']} />
                        <mesh name="Object_18_5" geometry={nodes.Object_18_5.geometry} material={materials['lambert18SG.001']} />
                        <mesh name="Object_18_6" geometry={nodes.Object_18_6.geometry} material={materials['lambert21SG.001']} />
                        <mesh name="Object_18_7" geometry={nodes.Object_18_7.geometry} material={materials['lambert27SG.001']} />
                        <mesh name="Object_18_8" geometry={nodes.Object_18_8.geometry} material={materials['lambert29SG.001']} />
                        <mesh name="Object_18_9" geometry={nodes.Object_18_9.geometry} material={materials['lambert11SG.001']} />
                        <mesh name="Object_18_10" geometry={nodes.Object_18_10.geometry} material={materials['lambert13SG.001']} />
                        <mesh name="Object_18_11" geometry={nodes.Object_18_11.geometry} material={materials['lambert14SG.001']} />
                        <mesh name="Object_18_12" geometry={nodes.Object_18_12.geometry} material={materials['lambert15SG.001']} />
                        <mesh name="Object_18_13" geometry={nodes.Object_18_13.geometry} material={materials['lambert22SG.001']} />
                        <mesh name="Object_18_14" geometry={nodes.Object_18_14.geometry} material={materials['lambert23SG.001']} />
                        <mesh name="Object_18_15" geometry={nodes.Object_18_15.geometry} material={materials['lambert28SG.001']} />
                        <mesh name="Object_18_16" geometry={nodes.Object_18_16.geometry} material={materials['lambert3SG.001']} />
                        <mesh name="Object_18_17" geometry={nodes.Object_18_17.geometry} material={materials['lambert4SG.001']} />
                        <mesh name="Object_18_18" geometry={nodes.Object_18_18.geometry} material={materials['lambert5SG.001']} />
                        <mesh name="Object_18_19" geometry={nodes.Object_18_19.geometry} material={materials['lambert6SG.001']} />
                        <mesh name="Object_18_20" geometry={nodes.Object_18_20.geometry} material={materials['lambert8SG.001']} />
                        <mesh name="Object_18_21" geometry={nodes.Object_18_21.geometry} material={materials['pasted__pasted__lambert8SG1.001']} />
                    </group>
                    <group name="Object_21001" position={[-0.18, -1.88, 0.11]} rotation={[1.49, -0.15, -0.19]} scale={0.5}>
                        <mesh name="Object_18001" geometry={nodes.Object_18001.geometry} material={materials['initialShadingGroup.001']} />
                        <mesh name="Object_18001_1" geometry={nodes.Object_18001_1.geometry} material={materials['lambert10SG.001']} />
                        <mesh name="Object_18001_2" geometry={nodes.Object_18001_2.geometry} material={materials['lambert16SG.001']} />
                        <mesh name="Object_18001_3" geometry={nodes.Object_18001_3.geometry} material={materials['lambert17SG.001']} />
                        <mesh name="Object_18001_4" geometry={nodes.Object_18001_4.geometry} material={materials['lambert18SG.001']} />
                        <mesh name="Object_18001_5" geometry={nodes.Object_18001_5.geometry} material={materials['lambert21SG.001']} />
                        <mesh name="Object_18001_6" geometry={nodes.Object_18001_6.geometry} material={materials['lambert27SG.001']} />
                        <mesh name="Object_18001_7" geometry={nodes.Object_18001_7.geometry} material={materials['lambert11SG.001']} />
                        <mesh name="Object_18001_8" geometry={nodes.Object_18001_8.geometry} material={materials['lambert13SG.001']} />
                        <mesh name="Object_18001_9" geometry={nodes.Object_18001_9.geometry} material={materials['lambert14SG.001']} />
                        <mesh name="Object_18001_10" geometry={nodes.Object_18001_10.geometry} material={materials['lambert15SG.001']} />
                        <mesh name="Object_18001_11" geometry={nodes.Object_18001_11.geometry} material={materials['lambert22SG.001']} />
                        <mesh name="Object_18001_12" geometry={nodes.Object_18001_12.geometry} material={materials['lambert23SG.001']} />
                        <mesh name="Object_18001_13" geometry={nodes.Object_18001_13.geometry} material={materials['lambert3SG.001']} />
                        <mesh name="Object_18001_14" geometry={nodes.Object_18001_14.geometry} material={materials['lambert4SG.001']} />
                        <mesh name="Object_18001_15" geometry={nodes.Object_18001_15.geometry} material={materials['lambert5SG.001']} />
                        <mesh name="Object_18001_16" geometry={nodes.Object_18001_16.geometry} material={materials['lambert6SG.001']} />
                        <mesh name="Object_18001_17" geometry={nodes.Object_18001_17.geometry} material={materials['lambert8SG.001']} />
                    </group>
                    <group name="Object_21002" position={[0.08, -1.89, 0.13]} rotation={[1.51, -0.02, 2.94]} scale={0.5}>
                        <mesh name="Object_18002" geometry={nodes.Object_18002.geometry} material={materials['lambert30SG.001']} />
                        <mesh name="Object_18002_1" geometry={nodes.Object_18002_1.geometry} material={materials['initialShadingGroup.001']} />
                        <mesh name="Object_18002_2" geometry={nodes.Object_18002_2.geometry} material={materials['lambert10SG.001']} />
                        <mesh name="Object_18002_3" geometry={nodes.Object_18002_3.geometry} material={materials['lambert16SG.001']} />
                        <mesh name="Object_18002_4" geometry={nodes.Object_18002_4.geometry} material={materials['lambert17SG.001']} />
                        <mesh name="Object_18002_5" geometry={nodes.Object_18002_5.geometry} material={materials['lambert18SG.001']} />
                        <mesh name="Object_18002_6" geometry={nodes.Object_18002_6.geometry} material={materials['lambert21SG.001']} />
                        <mesh name="Object_18002_7" geometry={nodes.Object_18002_7.geometry} material={materials['lambert27SG.001']} />
                        <mesh name="Object_18002_8" geometry={nodes.Object_18002_8.geometry} material={materials['lambert29SG.001']} />
                        <mesh name="Object_18002_9" geometry={nodes.Object_18002_9.geometry} material={materials['lambert11SG.001']} />
                        <mesh name="Object_18002_10" geometry={nodes.Object_18002_10.geometry} material={materials['lambert13SG.001']} />
                        <mesh name="Object_18002_11" geometry={nodes.Object_18002_11.geometry} material={materials['lambert14SG.001']} />
                        <mesh name="Object_18002_12" geometry={nodes.Object_18002_12.geometry} material={materials['lambert15SG.001']} />
                        <mesh name="Object_18002_13" geometry={nodes.Object_18002_13.geometry} material={materials['lambert22SG.001']} />
                        <mesh name="Object_18002_14" geometry={nodes.Object_18002_14.geometry} material={materials['lambert23SG.001']} />
                        <mesh name="Object_18002_15" geometry={nodes.Object_18002_15.geometry} material={materials['lambert28SG.001']} />
                        <mesh name="Object_18002_16" geometry={nodes.Object_18002_16.geometry} material={materials['lambert3SG.001']} />
                        <mesh name="Object_18002_17" geometry={nodes.Object_18002_17.geometry} material={materials['lambert4SG.001']} />
                        <mesh name="Object_18002_18" geometry={nodes.Object_18002_18.geometry} material={materials['lambert5SG.001']} />
                        <mesh name="Object_18002_19" geometry={nodes.Object_18002_19.geometry} material={materials['lambert6SG.001']} />
                        <mesh name="Object_18002_20" geometry={nodes.Object_18002_20.geometry} material={materials['lambert8SG.001']} />
                        <mesh name="Object_18002_21" geometry={nodes.Object_18002_21.geometry} material={materials['pasted__pasted__lambert8SG1.001']} />
                    </group>
                    <group name="Object_21003" position={[0.06, -1.91, 0.01]} rotation={[1.53, -0.06, 2.89]} scale={0.5}>
                        <mesh name="Object_18003" geometry={nodes.Object_18003.geometry} material={materials['initialShadingGroup.001']} />
                        <mesh name="Object_18003_1" geometry={nodes.Object_18003_1.geometry} material={materials['lambert10SG.001']} />
                        <mesh name="Object_18003_2" geometry={nodes.Object_18003_2.geometry} material={materials['lambert16SG.001']} />
                        <mesh name="Object_18003_3" geometry={nodes.Object_18003_3.geometry} material={materials['lambert17SG.001']} />
                        <mesh name="Object_18003_4" geometry={nodes.Object_18003_4.geometry} material={materials['lambert18SG.001']} />
                        <mesh name="Object_18003_5" geometry={nodes.Object_18003_5.geometry} material={materials['lambert21SG.001']} />
                        <mesh name="Object_18003_6" geometry={nodes.Object_18003_6.geometry} material={materials['lambert27SG.001']} />
                        <mesh name="Object_18003_7" geometry={nodes.Object_18003_7.geometry} material={materials['lambert11SG.001']} />
                        <mesh name="Object_18003_8" geometry={nodes.Object_18003_8.geometry} material={materials['lambert13SG.001']} />
                        <mesh name="Object_18003_9" geometry={nodes.Object_18003_9.geometry} material={materials['lambert14SG.001']} />
                        <mesh name="Object_18003_10" geometry={nodes.Object_18003_10.geometry} material={materials['lambert15SG.001']} />
                        <mesh name="Object_18003_11" geometry={nodes.Object_18003_11.geometry} material={materials['lambert22SG.001']} />
                        <mesh name="Object_18003_12" geometry={nodes.Object_18003_12.geometry} material={materials['lambert23SG.001']} />
                        <mesh name="Object_18003_13" geometry={nodes.Object_18003_13.geometry} material={materials['lambert3SG.001']} />
                        <mesh name="Object_18003_14" geometry={nodes.Object_18003_14.geometry} material={materials['lambert4SG.001']} />
                        <mesh name="Object_18003_15" geometry={nodes.Object_18003_15.geometry} material={materials['lambert5SG.001']} />
                        <mesh name="Object_18003_16" geometry={nodes.Object_18003_16.geometry} material={materials['lambert6SG.001']} />
                        <mesh name="Object_18003_17" geometry={nodes.Object_18003_17.geometry} material={materials['lambert8SG.001']} />
                    </group>
                    <mesh name="tower004" geometry={nodes.tower004.geometry} material={materials.tower} position={[0.1, -0.43, 2.17]} rotation={[0.18, 0.04, -2.35]} scale={0.5} />
                    <group name="stadium001004" position={[-0.61, -1.12, -1.5]} rotation={[-2.17, -0.29, 0.38]} scale={1.25}>
                        <mesh name="Mesh090" geometry={nodes.Mesh090.geometry} material={materials.stadium} />
                        <mesh name="Mesh090_1" geometry={nodes.Mesh090_1.geometry} material={materials.car1} />
                        <mesh name="Mesh090_2" geometry={nodes.Mesh090_2.geometry} material={materials.windows} />
                        <mesh name="Mesh090_3" geometry={nodes.Mesh090_3.geometry} material={materials.car2} />
                    </group>
                    <group name="Boat_004_Sail_Boat_Wood_0001" rotation={[Math.PI / 2, 0, 0]}>
                        <mesh name="Mesh003" geometry={nodes.Mesh003.geometry} material={materials.Sail_Boat_Wood} />
                        <mesh name="Mesh003_1" geometry={nodes.Mesh003_1.geometry} material={materials.Sail_Boat_Sail} />
                    </group>
                    <group name="Sail_Front_003_Sail_Boat_Sail_0001" rotation={[Math.PI / 2, 0, 0]}>
                        <mesh name="Mesh011" geometry={nodes.Mesh011.geometry} material={materials.Sail_Boat_Sail} />
                        <mesh name="Mesh011_1" geometry={nodes.Mesh011_1.geometry} material={materials.Sail_Boat_Wood} />
                    </group>
                    <group name="Boat_002_Sail_Boat_Wood_0001" rotation={[Math.PI / 2, 0, 0]}>
                        <mesh name="Mesh012" geometry={nodes.Mesh012.geometry} material={materials.Sail_Boat_Wood} />
                        <mesh name="Mesh012_1" geometry={nodes.Mesh012_1.geometry} material={materials.Sail_Boat_Sail} />
                    </group>
                    <group name="Boat_001_Sail_Boat_Wood_0001" rotation={[Math.PI / 2, 0, 0]}>
                        <mesh name="Mesh013" geometry={nodes.Mesh013.geometry} material={materials.Sail_Boat_Wood} />
                        <mesh name="Mesh013_1" geometry={nodes.Mesh013_1.geometry} material={materials.Sail_Boat_Sail} />
                    </group>
                    <group name="Mast_Sail_Boat_Wood_0001" rotation={[Math.PI / 2, 0, 0]}>
                        <mesh name="Mesh015" geometry={nodes.Mesh015.geometry} material={materials.Sail_Boat_Wood} />
                        <mesh name="Mesh015_1" geometry={nodes.Mesh015_1.geometry} material={materials.Sail_Boat_Sail} />
                    </group>
                    <group name="Snow_Pine_023_Tree_Bark_0001" rotation={[Math.PI / 2, 0, 0]}>
                        <mesh name="Mesh016" geometry={nodes.Mesh016.geometry} material={materials.Tree_Bark} />
                        <mesh name="Mesh016_1" geometry={nodes.Mesh016_1.geometry} material={materials.House_Chimney} />
                        <mesh name="Mesh016_2" geometry={nodes.Mesh016_2.geometry} material={materials.Snow} />
                        <mesh name="Mesh016_3" geometry={nodes.Mesh016_3.geometry} material={materials.House_Roof} />
                        <mesh name="Mesh016_4" geometry={nodes.Mesh016_4.geometry} material={materials.House} />
                        <mesh name="Mesh016_5" geometry={nodes.Mesh016_5.geometry} material={materials.House_Door} />
                        <mesh name="Mesh016_6" geometry={nodes.Mesh016_6.geometry} material={materials.Tree_Leaves} />
                        <mesh name="Mesh016_7" geometry={nodes.Mesh016_7.geometry} material={materials.MountainNorth} />
                        <mesh name="Mesh016_8" geometry={nodes.Mesh016_8.geometry} material={materials.Grass} />
                    </group>
                    <group name="Cone_236_Tree_Leaves_0001" rotation={[Math.PI / 2, 0, 0]}>
                        <mesh name="Mesh017" geometry={nodes.Mesh017.geometry} material={materials.Tree_Leaves} />
                        <mesh name="Mesh017_1" geometry={nodes.Mesh017_1.geometry} material={materials.Tree_Bark} />
                        <mesh name="Mesh017_2" geometry={nodes.Mesh017_2.geometry} material={materials.House_Chimney} />
                        <mesh name="Mesh017_3" geometry={nodes.Mesh017_3.geometry} material={materials.House_Roof} />
                        <mesh name="Mesh017_4" geometry={nodes.Mesh017_4.geometry} material={materials.House} />
                        <mesh name="Mesh017_5" geometry={nodes.Mesh017_5.geometry} material={materials.House_Door} />
                    </group>
                    <group name="Cone_035_Tree_Leaves_0001" rotation={[Math.PI / 2, 0, 0]}>
                        <mesh name="Mesh023" geometry={nodes.Mesh023.geometry} material={materials.Tree_Leaves} />
                        <mesh name="Mesh023_1" geometry={nodes.Mesh023_1.geometry} material={materials.Tree_Bark} />
                    </group>
                    <group name="Base_010_House_Door_0001" rotation={[Math.PI / 2, 0, 0]}>
                        <mesh name="Mesh024" geometry={nodes.Mesh024.geometry} material={materials.House_Door} />
                        <mesh name="Mesh024_1" geometry={nodes.Mesh024_1.geometry} material={materials.House} />
                        <mesh name="Mesh024_2" geometry={nodes.Mesh024_2.geometry} material={materials.Pyramid} />
                    </group>
                    <group name="Cube_002_Bridge_0001" rotation={[Math.PI / 2, 0, 0]}>
                        <mesh name="Mesh025" geometry={nodes.Mesh025.geometry} material={materials.Bridge} />
                        <mesh name="Mesh025_1" geometry={nodes.Mesh025_1.geometry} material={materials.Rope} />
                    </group>
                    <mesh name="Cube_001_Bridge_0001" geometry={nodes.Cube_001_Bridge_0001.geometry} material={materials.Bridge} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh name="Cube_001_Rope_0001" geometry={nodes.Cube_001_Rope_0001.geometry} material={materials.Rope} rotation={[Math.PI / 2, 0, 0]} />
                    <group name="Cube_Bridge_0001" rotation={[Math.PI / 2, 0, 0]}>
                        <mesh name="Mesh029" geometry={nodes.Mesh029.geometry} material={materials.Bridge} />
                        <mesh name="Mesh029_1" geometry={nodes.Mesh029_1.geometry} material={materials.Rope} />
                    </group>
                    <mesh name="Planet_Snow_0001" geometry={nodes.Planet_Snow_0001.geometry} material={materials.Snow} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh name="Planet_Water_0001" geometry={nodes.Planet_Water_0001.geometry} material={materials.Water} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh name="Planet_Sand_0003" geometry={nodes.Planet_Sand_0003.geometry} material={materials.Sand} rotation={[Math.PI / 2, 0, 0]} />
                    <group name="Planet_Sand_0004" rotation={[Math.PI / 2, 0, 0]}>
                        <mesh name="Mesh035" geometry={nodes.Mesh035.geometry} material={materials.Sand} />
                        <mesh name="Mesh035_1" geometry={nodes.Mesh035_1.geometry} material={materials.Grass} />
                        <mesh name="Mesh035_2" geometry={nodes.Mesh035_2.geometry} material={materials.Asphalt} />
                    </group>
                    <group name="Planet_Sand_0005" rotation={[Math.PI / 2, 0, 0]}>
                        <mesh name="Mesh036" geometry={nodes.Mesh036.geometry} material={materials.Sand} />
                        <mesh name="Mesh036_1" geometry={nodes.Mesh036_1.geometry} material={materials.Grass} />
                        <mesh name="Mesh036_2" geometry={nodes.Mesh036_2.geometry} material={materials['Pavement.001']} />
                        <mesh name="Mesh036_3" geometry={nodes.Mesh036_3.geometry} material={materials['stadium grounds']} />
                    </group>
                    <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials.road} rotation={[-1.72, -0.6, 0]} scale={0.08} />
                    <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.road} rotation={[-2.29, 0.19, 0.69]} scale={0.08} />
                    <group name="Rocket_Ship_01003" rotation={[1.99, -0.52, 0.59]} scale={0.75}>
                        <mesh name="Mesh052" geometry={nodes.Mesh052.geometry} material={materials['Material #27']} />
                        <mesh name="Mesh052_1" geometry={nodes.Mesh052_1.geometry} material={materials['Material #28']} />
                        <mesh name="Mesh052_2" geometry={nodes.Mesh052_2.geometry} material={materials['Material #29']} />
                        <mesh name="Mesh052_3" geometry={nodes.Mesh052_3.geometry} material={materials.flame1} />
                        <mesh name="Mesh052_4" geometry={nodes.Mesh052_4.geometry} material={materials['Material #30']} />
                        <mesh name="Mesh052_5" geometry={nodes.Mesh052_5.geometry} material={materials.LaunchPad} />
                        <mesh name="Mesh052_6" geometry={nodes.Mesh052_6.geometry} material={materials['flame2.001']} />
                        <mesh name="Mesh052_7" geometry={nodes.Mesh052_7.geometry} material={materials.flame3} />
                        <mesh name="Mesh052_8" geometry={nodes.Mesh052_8.geometry} material={materials.Astronaut} />
                    </group>
                    <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['TextureGrid.001']} position={[-0.3, -1.78, -0.11]} rotation={[-0.36, -0.89, 2.74]} scale={0.5} />
                    <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={materials['Windmill.002']} position={[0.19, -1.69, 0.3]} rotation={[-1.91, 1.43, -1.48]} scale={0.5} />
                    <mesh ref={turbineBlade} name="Cylinder006" geometry={nodes.Cylinder006.geometry} material={materials['Windmill.002']} position={[0.3, -2.15, 0.42]} scale={0.5} />
                    <mesh name="airplane" geometry={nodes.airplane.geometry} material={materials['initialShadingGroup.002']} position={[-0.55, -1.65, 0.39]} rotation={[-1.8, 0.33, 0.57]} scale={0.03} />
                    <mesh name="rollet_table002" geometry={nodes.rollet_table002.geometry} material={materials['rollet table.003']} position={[-1.54, -0.49, -0.95]} rotation={[1.4, 0.25, 2.15]} scale={0.25} />
                    <group name="Cone_035_Tree_Leaves_0003" rotation={[Math.PI / 2, 0, 0]}>
                        <mesh name="Mesh077" geometry={nodes.Mesh077.geometry} material={materials.Skyscraper} />
                        <mesh name="Mesh077_1" geometry={nodes.Mesh077_1.geometry} material={materials.SkyscraperWindow} />
                    </group>
                </group>
            </group>



            <group ref={satellite} name="node-0001" position={[4.04, 0.99, 0]} rotation={[0.36, 5.2, 1.6]} scale={0.48}>
                <mesh name="buffer-0-mesh-0001" geometry={nodes['buffer-0-mesh-0001'].geometry} material={materials['09___Default']} />
                <mesh name="buffer-0-mesh-0001_1" geometry={nodes['buffer-0-mesh-0001_1'].geometry} material={materials['08___Default']} />
            </group>
        </>
    )
}

useGLTF.preload('/Globe_v4.4.glb')


export default function App() {

    return (
        <Canvas>
            <PerspectiveCamera makeDefault position={[1, 0, 5]} fov={75}>
                <pointLight intensity={0.7} position={[-5, 15, 15]} />
                {/* <pointLight intensity={0.7} position={[-2, 5, 5]} /> */}
                <spotLight castShadow intensity={0.4} angle={0.2} penumbra={1} position={[-25, 20, -15]} shadow-mapSize={[1024, 1024]} shadow-bias={-0.0001} />
            </PerspectiveCamera>

            <Suspense fallback={null}>
                <Model2 />
                <Astronaut3D />
                <OrbitControls autoRotate={false} />
                {/* <ambientLight intensity={0.5} /> */}
                <Stars radius={500} depth={5} count={1000} factor={10} />
                {/* <directionalLight position={[-5, 5, 5]} castShadow shadow-mapSize-width={1024} shadow-mapSize-height={1024} /> */}
                {/* <shadowMaterial transparent opacity={0.2} /> */}
                <fog attach="fog" args={['#272730', 6, 30]} />

                {/* <spotLight position={[10, 10, 10]} intensity={.5} />
                <pointLight position={[0, 0, 0]} color={"#f6f3ea"} intensity={1.2} /> */}

                {/* <pointLight position={[0, 1, 1]} intensity={.5} /> */}
                {/* <pointLight position={[1, 1, 0]} intensity={.5} /> */}
                {/* <hemisphereLight intensity={.5} /> */}
                <ambientLight intensity={0.08} />
                {/* <Environment preset="studio" /> */}
                {/* <directionalLight position={[1, 1, 0]} castShadow={true} intensity={0.5} /> */}

            </Suspense>
        </Canvas>
    );
}